name: flutter_parse_chat
description: A Full-Fledged Chat package using parse server as a Backend
version: 0.0.1
homepage: https://github.com/mobile-open-chat/open-chat-parse-server-flutter-pkg

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.17.0"

# The database version
isar_version: &isar_version 3.0.2 # define the version to be used

dependencies:
  flutter:
    sdk: flutter

  # Notifications
  firebase_messaging: ^13.1.0
  awesome_notifications: ^0.7.2

  # Backend server
  parse_server_sdk_flutter: ^3.1.3

  # Utils & tools
  image_picker: ^0.8.6
  rxdart: ^0.27.5
  stream_transform: ^2.0.1
  get_it: ^7.2.0
  path_provider: ^2.0.11
  path: ^1.8.2
  permission_handler: ^10.1.0
  collection: ^1.16.0

  # For testing
  mocktail: ^0.3.0
  bloc_test: ^9.1.0

  # Data quality
  equatable: ^2.0.5

  # Database
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core

  # State management (Bloc)
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  isar_generator: *isar_version
  build_runner: any

flutter:
